# Generated by Django 5.2.10 on 2026-01-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='language',
            field=models.CharField(default='english', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='prompt',
            field=models.TextField(unique=True),
        ),
    ]
