# Generated by Django 5.2.10 on 2026-02-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0003_summaryhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('content_en', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
